version: '3'

# Use this file to override default, primary configuration in the docker-compose.yml file
# Example use:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml [command]

services:
    # The primary hadatac web app
    hadatac:
        volumes:
            # Mounts the local app directory to the app directory in the Docker container
            # Any changes made locally automatically show up in the Docker container.
            - ./app:/root/app/app
